from __future__ import annotations

from typing import Protocol

from backend.schemas import ConversationTurn, HintEvent, SessionState


class RuntimeRepository(Protocol):
    """LocalRuntime과 PostgreSQL Repository가 공유할 최소 저장 계약."""

    def save_session(self, session: SessionState) -> None: ...

    def get_session(self, session_id: str) -> SessionState | None: ...

    def append_hint_event(self, event: HintEvent) -> None: ...

    def list_hint_events(self, session_id: str, puzzle_id: str) -> list[HintEvent]: ...

    def get_idempotency(self, key: str) -> tuple[dict, dict] | None: ...

    def save_idempotency(self, key: str, payload: dict, result: dict) -> None: ...

    def save_master_request(self, request: dict) -> None: ...

    def get_master_request(self, request_id: str) -> dict | None: ...

    def update_master_request(self, request: dict) -> None: ...

    def list_master_requests(self) -> list[dict]: ...

    def append_conversation_turn(self, session_id: str, turn: ConversationTurn) -> None: ...

    def list_conversation_turns(self, session_id: str, limit: int = 6) -> list[ConversationTurn]: ...
